# Generated by Django 5.2.5 on 2025-09-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('id_no', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('disability', models.BooleanField(default=False)),
                ('physical_address', models.TextField()),
                ('tish_area', models.CharField(max_length=50)),
                ('ward_no', models.IntegerField()),
                ('contact_number', models.CharField(max_length=20)),
                ('race', models.CharField(max_length=1)),
                ('recovering_service_user', models.BooleanField(default=False)),
                ('social_grant', models.CharField(max_length=50)),
                ('cooperative_member', models.BooleanField(default=False)),
                ('sign', models.CharField(max_length=50)),
            ],
        ),
    ]
