# Generated by Django 5.2.5 on 2025-09-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('id_no_or_dob', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('LGBTQIA+', 'LGBTQIA+')], max_length=20)),
                ('disability', models.BooleanField(default=False, verbose_name='Disability (Yes/No)')),
                ('physical_address', models.CharField(max_length=200)),
                ('tish_area', models.CharField(max_length=100)),
                ('ward_no', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=20)),
                ('race', models.CharField(choices=[('A', 'African'), ('I', 'Indian'), ('C', 'Coloured'), ('W', 'White')], max_length=10)),
                ('recovering_service_user', models.BooleanField(default=False)),
                ('social_grant', models.CharField(choices=[('None', 'None'), ('CSG', 'CSG'), ('SRD', 'SRD'), ('Other', 'Other')], max_length=20, verbose_name='Social Grant Recipient')),
                ('cooperative_member', models.BooleanField(default=False)),
                ('signature_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/')),
            ],
        ),
    ]
