# Generated by Django 5.2.5 on 2025-09-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registryentry',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='registryentry',
            name='id_no',
        ),
        migrations.AddField(
            model_name='registryentry',
            name='id_no_or_dob',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='disability',
            field=models.BooleanField(default=False, verbose_name='Disability (Yes/No)'),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('LGBTQIA+', 'LGBTQIA+')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='physical_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='race',
            field=models.CharField(choices=[('A', 'African'), ('I', 'Indian'), ('C', 'Coloured'), ('W', 'White')], max_length=10),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='sign',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='social_grant',
            field=models.CharField(choices=[('None', 'None'), ('CSG', 'CSG'), ('SRD', 'SRD'), ('Other', 'Other')], max_length=20, verbose_name='Social Grant Recipient'),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='tish_area',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='ward_no',
            field=models.CharField(max_length=20),
        ),
    ]
