# Generated by Django 5.2.5 on 2025-09-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registryentry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Registry Entry', 'verbose_name_plural': 'Registry Entries'},
        ),
        migrations.AddField(
            model_name='registryentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='cooperative_member',
            field=models.BooleanField(default=False, verbose_name='Cooperative Member'),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='disability',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='id_no_or_dob',
            field=models.CharField(max_length=50, verbose_name='ID Number or Date of Birth'),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='physical_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='race',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Colored', 'Colored'), ('Indian', 'Indian'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='recovering_service_user',
            field=models.BooleanField(default=False, verbose_name='Recovering Service User'),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='signature_data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='social_grant',
            field=models.CharField(blank=True, max_length=100, verbose_name='Social Grant'),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='tish_area',
            field=models.CharField(blank=True, choices=[('', 'Select Area Type'), ('Hostel', 'Hostel'), ('Township', 'Township'), ('Informal Settlement', 'Informal Settlement')], max_length=50, verbose_name='TISH Area'),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='ward_no',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ward Number'),
        ),
    ]
