# Generated by Django 5.2.5 on 2025-09-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_alter_registryentry_options_registryentry_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registryentry',
            name='social_grant',
            field=models.CharField(blank=True, choices=[('None', 'No Social Grant'), ('CSG', 'Child Support Grant'), ('SRD', 'Social Relief Distress'), ('Older Persons', 'Older Persons Grant'), ('Disability', 'Disability Grant'), ('Foster Care', 'Foster Care Grant'), ('Other', 'Other Grant')], default='None', max_length=50, verbose_name='Social Grant Type'),
        ),
    ]
