# Generated by Django 5.2.5 on 2025-09-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_remove_registryentry_dob_remove_registryentry_id_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registryentry',
            name='sign',
        ),
        migrations.AddField(
            model_name='registryentry',
            name='signature_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registryentry',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
