# Generated by Django 5.2.5 on 2025-09-18 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_remove_registryentry_sign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registryentry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
