# Generated by Django 5.2.5 on 2025-09-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_alter_registryentry_social_grant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registryentry',
            options={},
        ),
        migrations.RemoveField(
            model_name='registryentry',
            name='signature_data',
        ),
        migrations.RemoveField(
            model_name='registryentry',
            name='signature_image',
        ),
        migrations.RemoveField(
            model_name='registryentry',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='cooperative_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='id_no_or_dob',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='names',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='physical_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='race',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='recovering_service_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='social_grant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='surname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='tish_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registryentry',
            name='ward_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
