# Generated by Django 5.2.5 on 2025-09-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_alter_registryentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registryentry',
            name='signature_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registryentry',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
