# Generated by Django 5.2.5 on 2025-09-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_registryentry_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registryentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
